#!/usr/bin/env python3
"""
generate_index.py — T4 skeleton equation index generator
==========================================================
Reads all YAML-frontmatter .md files in Paper/empirical_validations/,
validates required fields, and outputs Paper/empirical_index.tex — a
LaTeX longtable with one row per equation.

Usage (via Makefile):
    make index
    # or directly:
    python3 Paper/scripts/generate_index.py

Exit codes:
    0  — success (warnings for missing fields are acceptable at T4 stage)
    1  — parse error (YAML malformed; must be fixed before T9)
"""

from __future__ import annotations

import sys
import re
import textwrap
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR    = Path(__file__).resolve().parent
PAPER_DIR     = SCRIPT_DIR.parent
REGISTRY_DIR  = PAPER_DIR / "empirical_validations"
OUTPUT_TEX    = PAPER_DIR / "empirical_index.tex"

# ── Required fields (missing → warning, not error) ───────────────────────────
REQUIRED_FIELDS = [
    "label", "new_label", "chapter", "chapter_title",
    "line", "statement", "type", "tier", "status",
    "existing_case_study", "phase3_headline",
    "difficulty", "falsification",
]

# ── Tier descriptions ─────────────────────────────────────────────────────────
TIER_DESC = {
    1: "Peer-reviewed quantitative",
    2: "Public dataset + computation",
    3: "Ordinal / structural estimate",
}

# ── LaTeX helpers ─────────────────────────────────────────────────────────────

def _tex_escape(s: str) -> str:
    """Minimal LaTeX escaping for text content in table cells."""
    if not s:
        return ""
    s = str(s)
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&",  r"\&"),
        ("%",  r"\%"),
        ("$",  r"\$"),
        ("#",  r"\#"),
        ("_",  r"\_"),
        ("{",  r"\{"),
        ("}",  r"\}"),
        ("~",  r"\textasciitilde{}"),
        ("^",  r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        s = s.replace(old, new)
    return s


def _shorten(s: str, maxlen: int = 60) -> str:
    """Truncate and escape a string for a table cell."""
    if not s:
        return r"\textit{(pending)}"
    s = str(s).strip().replace("\n", " ")
    if len(s) > maxlen:
        s = s[:maxlen - 1] + "…"
    return _tex_escape(s)


def _tier_color(tier: int) -> str:
    """LaTeX color command for tier badge."""
    colors = {1: "green!60!black", 2: "blue!70!black", 3: "gray"}
    return colors.get(tier, "black")


def _status_badge(status: str) -> str:
    colors = {"complete": "green!60!black", "in_progress": "orange!80!black", "pending": "gray!60"}
    col = colors.get(status, "gray!60")
    return rf"\textcolor{{{col}}}{{\small\texttt{{{_tex_escape(status)}}}}}"


# ── Registry loader ───────────────────────────────────────────────────────────

def load_registry(registry_dir: Path) -> tuple[list[dict], list[str], list[str]]:
    """
    Load all eq_*.md files from registry_dir.
    Returns (records, warnings, errors).
    warnings: missing-field issues (acceptable at T4)
    errors:   parse failures (must fix before T9)
    """
    records: list[dict] = []
    warnings: list[str] = []
    errors:   list[str] = []

    md_files = sorted(registry_dir.glob("eq_*.md"))
    if not md_files:
        errors.append(f"No eq_*.md files found in {registry_dir}")
        return records, warnings, errors

    for fpath in md_files:
        raw = fpath.read_text(encoding="utf-8")
        # Split on YAML frontmatter delimiters
        parts = raw.split("---\n", 2)
        if len(parts) < 3:
            errors.append(f"{fpath.name}: could not find YAML frontmatter delimiters")
            continue
        try:
            fm = yaml.safe_load(parts[1])
        except yaml.YAMLError as exc:
            errors.append(f"{fpath.name}: YAML parse error — {exc}")
            continue
        if not isinstance(fm, dict):
            errors.append(f"{fpath.name}: frontmatter is not a YAML mapping")
            continue

        fm["_file"] = fpath.name
        records.append(fm)

        # Check required fields
        for field in REQUIRED_FIELDS:
            if field not in fm or fm[field] is None:
                warnings.append(f"{fpath.name}: missing field '{field}'")

    return records, warnings, errors


# ── LaTeX output ──────────────────────────────────────────────────────────────

_LONGTABLE_PREAMBLE = r"""% empirical_index.tex — auto-generated by Paper/scripts/generate_index.py (T4 skeleton)
% Do NOT edit manually. Regenerate with: make index
%
% Include in main document with:
%   \input{empirical_index}
%
% Requires: longtable, booktabs, xcolor, array (loaded in main preamble)

\begingroup
\small
\setlength{\LTpre}{6pt}
\setlength{\LTpost}{6pt}
\begin{longtable}{%
  >{\raggedright}p{1.8cm}   % label
  >{\centering}p{0.5cm}     % ch
  >{\raggedright}p{2.0cm}   % type
  >{\centering}p{0.5cm}     % tier
  >{\centering}p{0.5cm}     % diff
  >{\centering}p{0.8cm}     % status
  >{\raggedright}p{5.2cm}   % falsification (truncated)
}
\toprule
\textbf{Label} &
\textbf{Ch} &
\textbf{Type} &
\textbf{T} &
\textbf{D} &
\textbf{Status} &
\textbf{Falsification criterion (truncated)} \\
\midrule
\endfirsthead
\toprule
\textbf{Label} &
\textbf{Ch} &
\textbf{Type} &
\textbf{T} &
\textbf{D} &
\textbf{Status} &
\textbf{Falsification criterion (truncated)} \\
\midrule
\endhead
\midrule
\multicolumn{7}{r}{\small\itshape continued on next page} \\
\endfoot
\bottomrule
\endlastfoot
"""

_LONGTABLE_SUFFIX = r"""\end{longtable}
\endgroup
"""


def build_longtable(records: list[dict]) -> str:
    """Build the longtable body from sorted records."""
    # Sort by chapter, then by file name (preserves within-chapter seq order)
    records_sorted = sorted(
        records,
        key=lambda r: (r.get("chapter", 0), r.get("_file", "")),
    )

    rows: list[str] = []
    prev_chapter = None

    for rec in records_sorted:
        ch     = rec.get("chapter", "?")
        label  = str(rec.get("label", ""))
        typ    = str(rec.get("type", "structural"))
        tier   = int(rec.get("tier", 3))
        diff   = str(rec.get("difficulty", "M"))
        status = str(rec.get("status", "pending"))
        falsi  = str(rec.get("falsification", "") or "")
        p3     = rec.get("phase3_headline", False)

        # Chapter separator row
        if ch != prev_chapter:
            ch_title = _tex_escape(str(rec.get("chapter_title", f"Chapter {ch}")))
            if prev_chapter is not None:
                rows.append(r"\addlinespace[4pt]")
            rows.append(
                rf"\multicolumn{{7}}{{l}}{{\small\bfseries Chapter {ch}: {ch_title}}} \\"
            )
            rows.append(r"\midrule")
            prev_chapter = ch

        # Compose label cell — bold for Phase 3 headlines
        label_cell = rf"\texttt{{{_tex_escape(label)}}}"
        if p3:
            label_cell = rf"\textbf{{{label_cell}}}"

        tier_cell   = rf"\textcolor{{{_tier_color(tier)}}}{{{tier}}}"
        status_cell = _status_badge(status)
        falsi_cell  = _shorten(falsi, maxlen=70)
        type_cell   = _tex_escape(typ)

        row = (
            f"{label_cell} & {ch} & {type_cell} & "
            f"{tier_cell} & {diff} & {status_cell} & {falsi_cell} \\\\"
        )
        rows.append(row)

    return "\n".join(rows)


def write_tex(records: list[dict], n_valid: int, n_missing: int) -> None:
    body = build_longtable(records)
    comment_header = textwrap.dedent(f"""\
        % ── Empirical Validation Index ────────────────────────────────────────────
        % Generated: 2026-04-21
        % Equations: {len(records)} total | {n_valid} fully specified | {n_missing} with missing fields
        % Tier legend: 1=peer-reviewed quantitative  2=public dataset  3=ordinal/structural
        % Status: pending / in_progress / complete
        % Bold label = Phase 3 headline equation
        % ──────────────────────────────────────────────────────────────────────────

    """)
    OUTPUT_TEX.write_text(
        comment_header + _LONGTABLE_PREAMBLE + body + "\n" + _LONGTABLE_SUFFIX,
        encoding="utf-8",
    )


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> int:
    print(f"generate_index.py — reading {REGISTRY_DIR} …")

    records, warnings, errors = load_registry(REGISTRY_DIR)

    # Report errors (fatal)
    if errors:
        print(f"\n  ERRORS ({len(errors)}) — must fix before T9:")
        for e in errors:
            print(f"    ✗ {e}")
        print("\nAborting: parse errors present.", file=sys.stderr)
        return 1

    # Count missing-field records
    missing_field_files: set[str] = set()
    for w in warnings:
        fname = w.split(":")[0]
        missing_field_files.add(fname)

    n_valid   = len(records) - len(missing_field_files)
    n_missing = len(missing_field_files)

    # Report warnings (non-fatal)
    if warnings:
        print(f"\n  Warnings ({len(warnings)}) — missing fields acceptable at T4 stage:")
        for w in warnings[:20]:
            print(f"    ⚠  {w}")
        if len(warnings) > 20:
            print(f"    … and {len(warnings)-20} more (see full list above)")

    # Generate output
    write_tex(records, n_valid, n_missing)

    # Summary
    by_type: dict[str, int] = {}
    by_tier: dict[int, int] = {}
    for r in records:
        t = str(r.get("type", "structural"))
        ti = int(r.get("tier", 3))
        by_type[t] = by_type.get(t, 0) + 1
        by_tier[ti] = by_tier.get(ti, 0) + 1

    print(f"\n  ─── Summary ───────────────────────────────────────────────")
    print(f"  Files parsed   : {len(records)}")
    print(f"  Fully specified: {n_valid}")
    print(f"  Missing fields : {n_missing}")
    for t, n in sorted(by_type.items()):
        print(f"  type={t:<16}: {n}")
    for t, n in sorted(by_tier.items()):
        print(f"  tier={t}            : {n}")
    print(f"\n  Output → {OUTPUT_TEX}")
    print(f"  ─── Done ──────────────────────────────────────────────────")

    return 0


if __name__ == "__main__":
    sys.exit(main())
